#!/bin/bash
#
# suse_studio_firstboot
#

die() {
  echo >&2 "$*"
  exit 1
}

setup_local_sles_repos() {
# SLES 11 SP3 ISO extraction
mkdir -p /srv/tftpboot/suse-11.3/install/
mount /srv/tftpboot/iso/SLES-11-SP3-DVD-x86_64-GM-DVD1.iso /mnt
rsync -avP /mnt/ /srv/tftpboot/suse-11.3/install/
umount /mnt
  zypper --gpg-auto-import-keys refresh
  zypper ar --refresh file:///srv/tftpboot/suse-11.3/install/ "SLES 11 SP3 Media"
}

setup_local_cloud_repos() {
# SUSE Cloud ISO extraction
mkdir -p /srv/tftpboot/repos/Cloud/
mount /srv/tftpboot/iso/SUSE-CLOUD-3-x86_64-GM-DVD1.iso /mnt
rsync -avP /mnt/ /srv/tftpboot/repos/Cloud/
umount /mnt
  zypper --gpg-auto-import-keys refresh
  zypper ar --refresh file:///srv/tftpboot/repos/Cloud/ "SUSE-Cloud-3"
}

setup_local_smt_repo() {
  zypper ar -c -t yast2 iso:/?iso=/srv/tftpboot/iso/SLE-11-SP3-SMT-GM-Media1.iso "SMT for SLES11SP3"
  zypper --gpg-auto-import-keys refresh
  zypper in -y --auto-agree-with-licenses -t pattern SMT lamp_server   
}

install_cloud_admin() {
  zypper --gpg-auto-import-keys refresh
  zypper in -y --auto-agree-with-licenses --force-resolution -t pattern cloud_admin
  [[ $? -ne 0 ]] && die "Failed to install cloud_admin pattern"
}

main() {
  
  setup_local_sles_repos
  setup_local_cloud_repos
  setup_local_smt_repo
  
  install_cloud_admin    
}

main "$@"