#!/bin/bash -e
#
# This script is executed at the end of appliance creation.  Here you can do
# one-time actions to modify your appliance before it is ever used, like
# removing files and directories to make it smaller, creating symlinks,
# generating indexes, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance
# (oem = disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /.profile
. /image/.profile

# read in KIWI utility functions
. /.kconfig

# Auto-start services on boot
chkconfig ntp on
chkconfig sshd on

# Remove EULA on first boot
rm /etc/YaST2/licenses/license.txt

# Create mount point for ISO files
mkdir -p /srv/tftpboot/iso

# Create mountpoint directories for Cloud
for MOUNTPOINT in /srv/tftpboot/suse-11.3/install /srv/tftpboot/repos/Cloud /srv/tftpboot/suse-12.0/install/ /srv/tftpboot/suse-12.0/repos/Cloud/
do
    if [ ! -d $MOUNTPOINT ]
        then
    mkdir -p $MOUNTPOINT
    fi
done

# Remove zypper repos
rm -fv /etc/zypp/repos.d/*

# Pick the right firstboot.xml to use
sed -i.orig 's/firstboot.xml/firstboot-suse-cloud.xml/g' /etc/sysconfig/firstboot

# Enable firstboot
touch /var/lib/YaST2/reconfig_system

exit 0
