#!/bin/bash

# read in some variables
. /studio/profile

if [ -f /etc/init.d/suse_studio_firstboot ]; then
    echo ""
    printf "%*s" $COLUMNS |tr " " "="
    echo "  ____"
    echo "/@    ~-."
    echo "\/ __ .- |   SUSE OpenStack Cloud 5 Admin"
    echo " // //  @"
    echo ""
    echo "    Running prepare step 1"
    echo "    This will take several minutes..."
    printf "%*s" $COLUMNS |tr " " "="
    echo ""
fi
